# Generated by Django 5.0.7 on 2024-07-20 14:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_topic_room_host_room_participants_message_room_topic'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='participants',
        ),
    ]
